# Generated by Django 5.0 on 2026-09-02 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_classe_eleve_matiere_delete_salle_de_classe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiaisonParentEleve',
            fields=[
                ('id_liaison', models.AutoField(primary_key=True, serialize=False)),
                ('date_liaison', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liaisons_parents', to='administration.eleve')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='liaisons_eleves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='liaisonparenteleve',
            constraint=models.UniqueConstraint(fields=('parent', 'eleve'), name='unique_parent_eleve'),
        ),
    ]
