# Generated by Django 4.1.13 on 2026-09-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_liaisonparenteleve_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matiere',
            name='unique_matiere_par_classe',
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('nom', 'classe')},
        ),
    ]
