# Generated by Django 4.1.13 on 2026-09-10 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0004_remove_matiere_unique_matiere_par_classe_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='liaisonparenteleve',
            name='unique_parent_eleve',
        ),
        migrations.AlterUniqueTogether(
            name='liaisonparenteleve',
            unique_together={('parent', 'eleve')},
        ),
    ]
