# Generated by Django 5.0 on 2026-09-02 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0003_liaisonparenteleve_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id_absence', models.AutoField(primary_key=True, serialize=False)),
                ('date_absence', models.DateField()),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='administration.eleve')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='absences_saisies', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='administration.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id_bulletin', models.AutoField(primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='bulletins/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='administration.eleve')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_saisis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('type_evaluation', models.CharField(choices=[('controle_continu', 'Contrôle continu'), ('devoir_harmonise', 'Devoir harmonisé')], max_length=30)),
                ('sequence', models.PositiveSmallIntegerField(choices=[(1, 'Séquence 1'), (2, 'Séquence 2'), (3, 'Séquence 3'), (4, 'Séquence 4'), (5, 'Séquence 5'), (6, 'Séquence 6')])),
                ('moyenne', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administration.eleve')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administration.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Remarque',
            fields=[
                ('id_remarque', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('positif', 'Positif'), ('negatif', 'Négatif'), ('autre', 'Autre')], max_length=20)),
                ('contenu', models.TextField()),
                ('date_remarque', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarques', to='administration.eleve')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='remarques_saisies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id_sanction', models.AutoField(primary_key=True, serialize=False)),
                ('type_sanction', models.CharField(choices=[('avertissement', 'Avertissement'), ('blame', 'Blâme'), ('retenue', 'Retenue'), ('exclusion', 'Exclusion'), ('autre', 'Autre')], max_length=30)),
                ('motif', models.TextField()),
                ('date_sanction', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='administration.eleve')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_saisies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
