# Generated by Django 4.1.13 on 2026-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='motif',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('justifiee', 'Justifiée'), ('non-justifiee', 'Non justifiée'), ('autre', 'Autre')], default='non-justifiee', max_length=20),
        ),
    ]
