# Generated by Django 4.1.13 on 2026-09-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0002_absence_motif_absence_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='annee_scolaire',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='sequence',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Séquence 1'), (2, 'Séquence 2'), (3, 'Séquence 3'), (4, 'Séquence 4'), (5, 'Séquence 5'), (6, 'Séquence 6')], default=1),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='trimestre',
            field=models.CharField(choices=[('Trimestre 1', 'Trimestre 1'), ('Trimestre 2', 'Trimestre 2'), ('Trimestre 3', 'Trimestre 3')], default='Trimestre 1', max_length=20),
        ),
    ]
